FROM nginx:alpine

# Copia os arquivos estáticos do frontend
COPY ./frontend /usr/share/nginx/html

# Usa a configuração customizada do Nginx (se existir)
COPY ./frontend/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]