FROM nginx:alpine

# copia os arquivos do frontend
COPY ./frontend /usr/share/nginx/html

# usa a configuração do Nginx 
COPY ./frontend/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]